[2025-04-06T18:23:20.327+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ticker_sentiment_analysis.clean_finshots_data manual__2025-04-06T18:23:11.053061+00:00 [queued]>
[2025-04-06T18:23:20.336+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ticker_sentiment_analysis.clean_finshots_data manual__2025-04-06T18:23:11.053061+00:00 [queued]>
[2025-04-06T18:23:20.338+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-04-06T18:23:20.347+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): clean_finshots_data> on 2025-04-06 18:23:11.053061+00:00
[2025-04-06T18:23:20.351+0000] {standard_task_runner.py:57} INFO - Started process 247 to run task
[2025-04-06T18:23:20.354+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ticker_sentiment_analysis', 'clean_finshots_data', 'manual__2025-04-06T18:23:11.053061+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/ticker_sentiment_analysis.py', '--cfg-path', '/tmp/tmpvaf_6g1d']
[2025-04-06T18:23:20.357+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask clean_finshots_data
[2025-04-06T18:23:20.393+0000] {task_command.py:415} INFO - Running <TaskInstance: ticker_sentiment_analysis.clean_finshots_data manual__2025-04-06T18:23:11.053061+00:00 [running]> on host 57321fb4d6c5
[2025-04-06T18:23:20.445+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ticker_sentiment_analysis' AIRFLOW_CTX_TASK_ID='clean_finshots_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T18:23:11.053061+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-06T18:23:11.053061+00:00'
[2025-04-06T18:23:20.446+0000] {ticker_sentiment_analysis.py:65} INFO - Cleaning Finshots data
[2025-04-06T18:23:20.449+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ticker_sentiment_analysis.py", line 66, in clean_finshots_data
    df = pd.read_csv('/opt/airflow/data/finshots_raw.csv')
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1723, in _make_engine
    return mapping[engine](f, **self.options)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "parsers.pyx", line 586, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
[2025-04-06T18:23:20.460+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=ticker_sentiment_analysis, task_id=clean_finshots_data, execution_date=20250406T182311, start_date=20250406T182320, end_date=20250406T182320
[2025-04-06T18:23:20.465+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task clean_finshots_data (No columns to parse from file; 247)
[2025-04-06T18:23:20.492+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-04-06T18:23:20.518+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
